import { Game } from './types';

const gameUrls = [
  "https://playszgames.com/wp-content/uploads/unblocked/1v1-lol.html",
  "https://playszgames.com/wp-content/uploads/unblocked/11-11.html",
  "https://playszgames.com/wp-content/uploads/unblocked/12-minibattles.html",
  "https://playszgames.com/wp-content/uploads/unblocked/2048.html",
  "https://playszgames.com/wp-content/uploads/unblocked/3d-car-simulator.html",
  "https://playszgames.com/wp-content/uploads/unblocked/3d-moto-simulator-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/4th-and-goal-2022.html",
  "https://playszgames.com/wp-content/uploads/unblocked/4x4-drive-offroad.html",
  "https://playszgames.com/wp-content/uploads/unblocked/8-ball-pool.html",
  "https://playszgames.com/wp-content/uploads/unblocked/a-dance-of-fire-and-ice.html",
  "https://playszgames.com/wp-content/uploads/unblocked/adventure-drivers.html",
  "https://playszgames.com/wp-content/uploads/unblocked/air-hockey-championship-deluxe.html",
  "https://playszgames.com/wp-content/uploads/unblocked/among-us.html",
  "https://playszgames.com/wp-content/uploads/unblocked/aqua-thrills.html",
  "https://playszgames.com/wp-content/uploads/unblocked/arithmetica.html",
  "https://playszgames.com/wp-content/uploads/unblocked/athletics-hero.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basket-and-ball.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basket-bros.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basket-champs.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basket-swooshes.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basketball-legends.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basketball-line.html",
  "https://playszgames.com/wp-content/uploads/unblocked/basketball-stars.html",
  "https://playszgames.com/wp-content/uploads/unblocked/battle-wheels.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bearsus.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bike-trials-offroad-1.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bike-trials-winter-1.html",
  "https://playszgames.com/wp-content/uploads/unblocked/block-the-pig.html",
  "https://playszgames.com/wp-content/uploads/unblocked/blocky-cars.html",
  "https://playszgames.com/wp-content/uploads/unblocked/blocky-trials.html",
  "https://playszgames.com/wp-content/uploads/unblocked/blumgi-ball.html",
  "https://playszgames.com/wp-content/uploads/unblocked/blumgi-castle.html",
  "https://playszgames.com/wp-content/uploads/unblocked/blumgi-rocket.html",
  "https://playszgames.com/wp-content/uploads/unblocked/blumgi-slime.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bowling-stars.html",
  "https://playszgames.com/wp-content/uploads/unblocked/boxing-physics-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/brain-for-monster-truck.html",
  "https://playszgames.com/wp-content/uploads/unblocked/brain-test-3-tricky-quests.html",
  "https://playszgames.com/wp-content/uploads/unblocked/brain-test-tricky-puzzles.html",
  "https://playszgames.com/wp-content/uploads/unblocked/breaking-the-bank.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bubble-trouble.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bubble-trouble-3.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bullet-force.html",
  "https://playszgames.com/wp-content/uploads/unblocked/bumper-cars-soccer.html",
  "https://playszgames.com/wp-content/uploads/unblocked/burnin-rubber-5-xs.html",
  "https://playszgames.com/wp-content/uploads/unblocked/burnin-rubber-crash-n-burn.html",
  "https://playszgames.com/wp-content/uploads/unblocked/burnout-drift-seaport-max.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cannon-strike.html",
  "https://playszgames.com/wp-content/uploads/unblocked/car-climb-racing.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cars-thief.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cat-trap.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cats.html",
  "https://playszgames.com/wp-content/uploads/unblocked/chicken-merge.html",
  "https://playszgames.com/wp-content/uploads/unblocked/city-car-driving-stunt-master.html",
  "https://playszgames.com/wp-content/uploads/unblocked/city-rider.html",
  "https://playszgames.com/wp-content/uploads/unblocked/color-switch.html",
  "https://playszgames.com/wp-content/uploads/unblocked/crazy-cars.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cricket-world-cup.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cubes-king.html",
  "https://playszgames.com/wp-content/uploads/unblocked/cyber-cars-punk-racing.html",
  "https://playszgames.com/wp-content/uploads/unblocked/death-chase.html",
  "https://playszgames.com/wp-content/uploads/unblocked/death-run-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/deepest-sword.html",
  "https://playszgames.com/wp-content/uploads/unblocked/demolition-derby-crash-racing.html",
  "https://playszgames.com/wp-content/uploads/unblocked/detective-loupe-puzzle.html",
  "https://playszgames.com/wp-content/uploads/unblocked/dinosaur-game.html",
  "https://playszgames.com/wp-content/uploads/unblocked/doodle-champion-island.html",
  "https://playszgames.com/wp-content/uploads/unblocked/draw-the-hill.html",
  "https://playszgames.com/wp-content/uploads/unblocked/dreadhead-parkour.html",
  "https://playszgames.com/wp-content/uploads/unblocked/drive-mad.html",
  "https://playszgames.com/wp-content/uploads/unblocked/dunkers.html",
  "https://playszgames.com/wp-content/uploads/unblocked/earn-to-die.html",
  "https://playszgames.com/wp-content/uploads/unblocked/electron-dash.html",
  "https://playszgames.com/wp-content/uploads/unblocked/energy.html",
  "https://playszgames.com/wp-content/uploads/unblocked/escaping-the-prison.html",
  "https://playszgames.com/wp-content/uploads/unblocked/eugenes-life.html",
  "https://playszgames.com/wp-content/uploads/unblocked/extreme-car-driving-simulator.html",
  "https://playszgames.com/wp-content/uploads/unblocked/extreme-car-parking.html",
  "https://playszgames.com/wp-content/uploads/unblocked/fancy-pants.html",
  "https://playszgames.com/wp-content/uploads/unblocked/fancy-pants-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/fancy-pants-3.html",
  "https://playszgames.com/wp-content/uploads/unblocked/flappy-bird-origin.html",
  "https://playszgames.com/wp-content/uploads/unblocked/fleeing-the-complex.html",
  "https://playszgames.com/wp-content/uploads/unblocked/flying-car-simulator.html",
  "https://playszgames.com/wp-content/uploads/unblocked/foot-chinko.html",
  "https://playszgames.com/wp-content/uploads/unblocked/football-masters.html",
  "https://playszgames.com/wp-content/uploads/unblocked/free-kick-shooter.html",
  "https://playszgames.com/wp-content/uploads/unblocked/free-the-key.html",
  "https://playszgames.com/wp-content/uploads/unblocked/furious-racing-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/g-switch-3.html",
  "https://playszgames.com/wp-content/uploads/unblocked/getaway-shootout.html",
  "https://playszgames.com/wp-content/uploads/unblocked/gold-digger-frvr.html",
  "https://playszgames.com/wp-content/uploads/unblocked/golfinity.html",
  "https://playszgames.com/wp-content/uploads/unblocked/grand-prix-hero.html",
  "https://playszgames.com/wp-content/uploads/unblocked/gravity-soccer.html",
  "https://playszgames.com/wp-content/uploads/unblocked/gun-mayhem.html",
  "https://playszgames.com/wp-content/uploads/unblocked/gun-mayhem-3.html",
  "https://playszgames.com/wp-content/uploads/unblocked/head-soccer-2023.html",
  "https://playszgames.com/wp-content/uploads/unblocked/heads-arena-soccer-all-stars.html",
  "https://playszgames.com/wp-content/uploads/unblocked/heart-star-html5.html",
  "https://playszgames.com/wp-content/uploads/unblocked/highway-traffic.html",
  "https://playszgames.com/wp-content/uploads/unblocked/horse-shoeing.html",
  "https://playszgames.com/wp-content/uploads/unblocked/icy-purple-head-3.html",
  "https://playszgames.com/wp-content/uploads/unblocked/idle-ants.html",
  "https://playszgames.com/wp-content/uploads/unblocked/idle-digging-tycoon.html",
  "https://playszgames.com/wp-content/uploads/unblocked/idle-mining-empire.html",
  "https://playszgames.com/wp-content/uploads/unblocked/idle-startup-tycoon.html",
  "https://playszgames.com/wp-content/uploads/unblocked/impossible-tic-tac-toe.html",
  "https://playszgames.com/wp-content/uploads/unblocked/infinity-loop.html",
  "https://playszgames.com/wp-content/uploads/unblocked/jetpack-joyride.html",
  "https://playszgames.com/wp-content/uploads/unblocked/jollyworld.html",
  "https://playszgames.com/wp-content/uploads/unblocked/kawaii-dressup.html",
  "https://playszgames.com/wp-content/uploads/unblocked/leader-strike.html",
  "https://playszgames.com/wp-content/uploads/unblocked/life-the-game.html",
  "https://playszgames.com/wp-content/uploads/unblocked/ludo-multiplayer.html",
  "https://playszgames.com/wp-content/uploads/unblocked/mad-truck-challenge-special.html",
  "https://playszgames.com/wp-content/uploads/unblocked/marble-dash.html",
  "https://playszgames.com/wp-content/uploads/unblocked/masked-forces.html",
  "https://playszgames.com/wp-content/uploads/unblocked/master-chess.html",
  "https://playszgames.com/wp-content/uploads/unblocked/maze-path-of-light.html",
  "https://playszgames.com/wp-content/uploads/unblocked/maze-planet-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/merge-cyber-racers.html",
  "https://playszgames.com/wp-content/uploads/unblocked/merge-round-racers.html",
  "https://playszgames.com/wp-content/uploads/unblocked/minibattles.html",
  "https://playszgames.com/wp-content/uploads/unblocked/minesweeper.html",
  "https://playszgames.com/wp-content/uploads/unblocked/monster-tracks.html",
  "https://playszgames.com/wp-content/uploads/unblocked/monsters-wheels-special.html",
  "https://playszgames.com/wp-content/uploads/unblocked/mosaic-puzzle-art.html",
  "https://playszgames.com/wp-content/uploads/unblocked/moto-maniac.html",
  "https://playszgames.com/wp-content/uploads/unblocked/moto-road-rash-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/moto-trial-racing-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/my-pony-my-little-race.html",
  "https://playszgames.com/wp-content/uploads/unblocked/n-gon.html",
  "https://playszgames.com/wp-content/uploads/unblocked/neon-war.html",
  "https://playszgames.com/wp-content/uploads/unblocked/noob-drive.html",
  "https://playszgames.com/wp-content/uploads/unblocked/offroader-v5.html",
  "https://playszgames.com/wp-content/uploads/unblocked/orbital-survival.html",
  "https://playszgames.com/wp-content/uploads/unblocked/paper-fighter-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/ping-pong-html5.html",
  "https://playszgames.com/wp-content/uploads/unblocked/pixel-gun-survival.html",
  "https://playszgames.com/wp-content/uploads/unblocked/pixwars-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/plactions.html",
  "https://playszgames.com/wp-content/uploads/unblocked/pool-club.html",
  "https://playszgames.com/wp-content/uploads/unblocked/poor-bunny.html",
  "https://playszgames.com/wp-content/uploads/unblocked/pop-it-master.html",
  "https://playszgames.com/wp-content/uploads/unblocked/power-badminton.html",
  "https://playszgames.com/wp-content/uploads/unblocked/raft-wars-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/raft-wars-multiplayer.html",
  "https://playszgames.com/wp-content/uploads/unblocked/raft-wars.html",
  "https://playszgames.com/wp-content/uploads/unblocked/rally-champion.html",
  "https://playszgames.com/wp-content/uploads/unblocked/real-cars-in-city.html",
  "https://playszgames.com/wp-content/uploads/unblocked/real-simulator-monster-truck.html",
  "https://playszgames.com/wp-content/uploads/unblocked/recoil.html",
  "https://playszgames.com/wp-content/uploads/unblocked/riddle-school.html",
  "https://playszgames.com/wp-content/uploads/unblocked/rocket-pult.html",
  "https://playszgames.com/wp-content/uploads/unblocked/rolly-vortex.html",
  "https://playszgames.com/wp-content/uploads/unblocked/roly-poly-monsters.html",
  "https://playszgames.com/wp-content/uploads/unblocked/rooftop-snipers-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/rowdy-wrestling.html",
  "https://playszgames.com/wp-content/uploads/unblocked/running-fred.html",
  "https://playszgames.com/wp-content/uploads/unblocked/rusher-crusher.html",
  "https://playszgames.com/wp-content/uploads/unblocked/school-bus-demolition-derby.html",
  "https://playszgames.com/wp-content/uploads/unblocked/scrap-metal.html",
  "https://playszgames.com/wp-content/uploads/unblocked/shoot-stickman.html",
  "https://playszgames.com/wp-content/uploads/unblocked/short-life.html",
  "https://playszgames.com/wp-content/uploads/unblocked/shortcut-race.html",
  "https://playszgames.com/wp-content/uploads/unblocked/skiing-fred.html",
  "https://playszgames.com/wp-content/uploads/unblocked/sketchbook-04.html",
  "https://playszgames.com/wp-content/uploads/unblocked/slime-road.html",
  "https://playszgames.com/wp-content/uploads/unblocked/slope-2-multiplayer.html",
  "https://playszgames.com/wp-content/uploads/unblocked/slope-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/slope-city.html",
  "https://playszgames.com/wp-content/uploads/unblocked/soccar.html",
  "https://playszgames.com/wp-content/uploads/unblocked/soccer-random.html",
  "https://playszgames.com/wp-content/uploads/unblocked/soccer-skills-champions-league.html",
  "https://playszgames.com/wp-content/uploads/unblocked/soccer-skills-euro-cup.html",
  "https://playszgames.com/wp-content/uploads/unblocked/solitaire.html",
  "https://playszgames.com/wp-content/uploads/unblocked/speed-boat-extreme-racing.html",
  "https://playszgames.com/wp-content/uploads/unblocked/squish-run.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stacktris.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stair-race-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stick-defenders.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stick-fighter.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stick-merge.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-army-team-battle.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-army-the-resistance.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-bike-pr.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-bike.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-boxing-ko-champion.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-bridge-constructor.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-climb-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stickman-golf.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stock-car-hero.html",
  "https://playszgames.com/wp-content/uploads/unblocked/street-ball-jam.html",
  "https://playszgames.com/wp-content/uploads/unblocked/striker-dummies.html",
  "https://playszgames.com/wp-content/uploads/unblocked/stunt-car-challenge-3.html",
  "https://playszgames.com/wp-content/uploads/unblocked/subway-runner.html",
  "https://playszgames.com/wp-content/uploads/unblocked/subway-surfers-newyork.html",
  "https://playszgames.com/wp-content/uploads/unblocked/subway-surfers-san-francisco.html",
  "https://playszgames.com/wp-content/uploads/unblocked/super-liquid-soccer.html",
  "https://playszgames.com/wp-content/uploads/unblocked/super-racing-gt-drag-pro.html",
  "https://playszgames.com/wp-content/uploads/unblocked/super-star-car.html",
  "https://playszgames.com/wp-content/uploads/unblocked/super-tunnel-rush.html",
  "https://playszgames.com/wp-content/uploads/unblocked/superbattle-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/superbike-hero.html",
  "https://playszgames.com/wp-content/uploads/unblocked/swingo.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tag.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tank-trouble-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tanuki-sunset.html",
  "https://playszgames.com/wp-content/uploads/unblocked/temple-run-2.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tennis-masters.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tetris-flash.html",
  "https://playszgames.com/wp-content/uploads/unblocked/the-spear-stickman.html",
  "https://playszgames.com/wp-content/uploads/unblocked/thumb-fighter-christmas.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tinytownracing.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tomb-of-the-mask-color.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tomb-of-the-mask.html",
  "https://playszgames.com/wp-content/uploads/unblocked/top-speed-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/traffic-mania.html",
  "https://playszgames.com/wp-content/uploads/unblocked/truck-traffic.html",
  "https://playszgames.com/wp-content/uploads/unblocked/tube-jumpers.html",
  "https://playszgames.com/wp-content/uploads/unblocked/two-ball-3d-dark.html",
  "https://playszgames.com/wp-content/uploads/unblocked/two-neon-boxes.html",
  "https://playszgames.com/wp-content/uploads/unblocked/ultimate-car-driving.html",
  "https://playszgames.com/wp-content/uploads/unblocked/unicycle-hero.html",
  "https://playszgames.com/wp-content/uploads/unblocked/vex-4.html",
  "https://playszgames.com/wp-content/uploads/unblocked/vex-5.html",
  "https://playszgames.com/wp-content/uploads/unblocked/vex-6.html",
  "https://playszgames.com/wp-content/uploads/unblocked/vex-7.html",
  "https://playszgames.com/wp-content/uploads/unblocked/volleyball-challenge.html",
  "https://playszgames.com/wp-content/uploads/unblocked/water-color-sort.html",
  "https://playszgames.com/wp-content/uploads/unblocked/where-is-my-cat.html",
  "https://playszgames.com/wp-content/uploads/unblocked/who-is.html",
  "https://playszgames.com/wp-content/uploads/unblocked/wizard-mike.html",
  "https://playszgames.com/wp-content/uploads/unblocked/wood-blocks-3d.html",
  "https://playszgames.com/wp-content/uploads/unblocked/word-city-crossed.html",
  "https://playszgames.com/wp-content/uploads/unblocked/word-city-uncrossed.html",
  "https://playszgames.com/wp-content/uploads/unblocked/wordle-unlimited.html",
  "https://playszgames.com/wp-content/uploads/unblocked/wrassling.html",
  "https://playszgames.com/wp-content/uploads/unblocked/zombie-derby-pixel-survival.html",
];

export const CATEGORIES = [
  'All', 'Action', 'Adventure', 'Driving', 'Multiplayer', 'Puzzle', 'Racing', 'Shooting', 'Sports', 'Stickman', 'Strategy', 'Skill'
];

const toTitleCase = (str: string) => {
  return str.replace(/-/g, ' ').replace(/\w\S*/g, (txt) => {
    return txt.charAt(0).toUpperCase() + txt.substring(1).toLowerCase();
  });
};

const getCategoryForGame = (name: string): string => {
    const lowerName = name.toLowerCase();
    if (lowerName.includes('car') || lowerName.includes('moto') || lowerName.includes('drift') || lowerName.includes('truck') || lowerName.includes('drive')) return 'Driving';
    if (lowerName.includes('race') || lowerName.includes('rally')) return 'Racing';
    if (lowerName.includes('soccer') || lowerName.includes('basket') || lowerName.includes('football') || lowerName.includes('golf') || lowerName.includes('pool') || lowerName.includes('cricket') || lowerName.includes('tennis')) return 'Sports';
    if (lowerName.includes('gun') || lowerName.includes('shoot') || lowerName.includes('force') || lowerName.includes('strike') || lowerName.includes('sniper')) return 'Shooting';
    if (lowerName.includes('stickman')) return 'Stickman';
    if (lowerName.includes('2') || lowerName.includes('two') || lowerName.includes('bros') || lowerName.includes('multiplayer')) return 'Multiplayer';
    if (lowerName.includes('fight') || lowerName.includes('mayhem') || lowerName.includes('wars') || lowerName.includes('battle') || lowerName.includes('derby')) return 'Action';
    if (lowerName.includes('puzzle') || lowerName.includes('brain') || lowerName.includes('word') || lowerName.includes('chess') || lowerName.includes('solitaire') || lowerName.includes('block') || lowerName.includes('maze')) return 'Puzzle';
    if (lowerName.includes('adventure') || lowerName.includes('vex') || lowerName.includes('escaping') || lowerName.includes('temple') || lowerName.includes('fancy-pants')) return 'Adventure';
    if (lowerName.includes('idle') || lowerName.includes('tycoon') || lowerName.includes('merge')) return 'Strategy';
    if (lowerName.includes('slope') || lowerName.includes('run') || lowerName.includes('dash') || lowerName.includes('fly') || lowerName.includes('color-switch')) return 'Skill';
    
    const fallbackCategories = ['Action', 'Skill', 'Adventure', 'Puzzle'];
    const hash = lowerName.split('').reduce((acc, char) => acc + char.charCodeAt(0), 0);
    return fallbackCategories[hash % fallbackCategories.length];
};

// Use a Set to store unique URLs
const uniqueGameUrls = [...new Set(gameUrls)];

export const GAMES: Game[] = uniqueGameUrls.map((url) => {
  const path = url.split('/').pop() || '';
  const id = path.replace('.html', '');
  const name = toTitleCase(id);
  const thumbnail = `https://abinbins.github.io/thumb/${id}.png`;
  
  return {
    id,
    name,
    category: getCategoryForGame(name),
    src: url,
    thumbnail,
  };
});